/* ================================================
   MTG.BROKER — Social Media Graphics Generator
   Cloudflare Pages Bundle v2.0

   This script:
   1. Injects the CSS (inlined by Vite at build time)
   2. Renders the full HTML UI into the mount point
   3. Loads the SMG canvas engine from the Cloudflare Worker
   ================================================ */

// Import CSS as raw string so we can inject it via <style> tag.
// This ensures a single JS output file with no separate CSS.
import cssText from './styles.css?raw';

// Inject CSS into the page
var styleEl = document.createElement('style');
styleEl.textContent = cssText;
document.head.appendChild(styleEl);

// Engine version — bump this when the worker deploys a new engine version
var ENGINE_VERSION = '1.8.22';
var ENGINE_URL = 'https://mtg-broker-social-media.rich-e00.workers.dev/static/social-media.js?v=' + ENGINE_VERSION;

// The full HTML template for the Social Media Graphics page
var PAGE_HTML = [
  '<div class="app-page-content">',
  '  <div class="app-container">',
  '',
  '    <!-- PAGE HEADER -->',
  '    <div class="sm-page-header">',
  '      <div class="sm-page-icon"><i class="fas fa-palette"></i></div>',
  '      <div>',
  '        <h1 class="sm-page-title">Social Media Graphics</h1>',
  '        <p class="sm-page-subtitle">Create professional, branded social media posts in seconds. Pick a template, enter your info, and download.</p>',
  '      </div>',
  '    </div>',
  '',
  '    <!-- MAIN LAYOUT -->',
  '    <div class="sm-layout">',
  '',
  '      <!-- COLUMN 1 — Design Settings -->',
  '      <div class="sm-col">',
  '',
  '        <!-- CARD 1: Template Type -->',
  '        <div class="sm-card">',
  '          <div class="sm-card-title"><i class="fas fa-th-large"></i> Template</div>',
  '          <div class="sm-template-grid">',
  '            <button class="sm-template-btn active" data-template="just-closed" onclick="SMG.setTemplate(\'just-closed\', this)">',
  '              <div class="template-icon"><i class="fas fa-home"></i></div>',
  '              <span class="template-label">Just Closed</span>',
  '            </button>',
  '            <button class="sm-template-btn" data-template="rate-update" onclick="SMG.setTemplate(\'rate-update\', this)">',
  '              <div class="template-icon"><i class="fas fa-chart-line"></i></div>',
  '              <span class="template-label">Rate Update</span>',
  '            </button>',
  '            <button class="sm-template-btn" data-template="testimonial" onclick="SMG.setTemplate(\'testimonial\', this)">',
  '              <div class="template-icon"><i class="fas fa-quote-right"></i></div>',
  '              <span class="template-label">Testimonial</span>',
  '            </button>',
  '            <button class="sm-template-btn" data-template="tips" onclick="SMG.setTemplate(\'tips\', this)">',
  '              <div class="template-icon"><i class="fas fa-lightbulb"></i></div>',
  '              <span class="template-label">Mortgage Tips</span>',
  '            </button>',
  '            <button class="sm-template-btn" data-template="new-listing" onclick="SMG.setTemplate(\'new-listing\', this)">',
  '              <div class="template-icon"><i class="fas fa-sign"></i></div>',
  '              <span class="template-label">New Listing</span>',
  '            </button>',
  '          </div>',
  '        </div>',
  '',
  '        <!-- CARD 2: Size -->',
  '        <div class="sm-card">',
  '          <div class="sm-card-title"><i class="fas fa-crop-alt"></i> Size</div>',
  '          <div class="sm-size-row">',
  '            <button class="sm-size-btn active" data-size="instagram" onclick="SMG.setSize(\'instagram\', this)">',
  '              <span class="size-label">Instagram</span>',
  '              <span class="size-dims">1080 &times; 1080</span>',
  '            </button>',
  '            <button class="sm-size-btn" data-size="facebook" onclick="SMG.setSize(\'facebook\', this)">',
  '              <span class="size-label">Facebook</span>',
  '              <span class="size-dims">1200 &times; 630</span>',
  '            </button>',
  '            <button class="sm-size-btn" data-size="story" onclick="SMG.setSize(\'story\', this)">',
  '              <span class="size-label">Story</span>',
  '              <span class="size-dims">1080 &times; 1920</span>',
  '            </button>',
  '          </div>',
  '        </div>',
  '',
  '        <!-- CARD 3: Font Sizes -->',
  '        <div class="sm-card">',
  '          <div class="sm-card-title"><i class="fas fa-text-height"></i> Font Size</div>',
  '          <div class="sm-color-sub-label">Main Section</div>',
  '          <div class="sm-fontsize-row" id="mainFontRow">',
  '            <button class="sm-fontsize-btn active" data-fontsize="small" onclick="SMG.setMainFontSize(\'small\', this)">',
  '              <span class="fs-label">S</span><span class="fs-hint">Small</span>',
  '            </button>',
  '            <button class="sm-fontsize-btn" data-fontsize="medium" onclick="SMG.setMainFontSize(\'medium\', this)">',
  '              <span class="fs-label">M</span><span class="fs-hint">Medium</span>',
  '            </button>',
  '            <button class="sm-fontsize-btn" data-fontsize="large" onclick="SMG.setMainFontSize(\'large\', this)">',
  '              <span class="fs-label">L</span><span class="fs-hint">Large</span>',
  '            </button>',
  '            <button class="sm-fontsize-btn" data-fontsize="xlarge" onclick="SMG.setMainFontSize(\'xlarge\', this)">',
  '              <span class="fs-label">XL</span><span class="fs-hint">Extra</span>',
  '            </button>',
  '          </div>',
  '          <div class="sm-color-sub-label">Bottom Bar</div>',
  '          <div class="sm-fontsize-row" id="barFontRow">',
  '            <button class="sm-fontsize-btn" data-fontsize="small" onclick="SMG.setBarFontSize(\'small\', this)">',
  '              <span class="fs-label">S</span><span class="fs-hint">Small</span>',
  '            </button>',
  '            <button class="sm-fontsize-btn active" data-fontsize="medium" onclick="SMG.setBarFontSize(\'medium\', this)">',
  '              <span class="fs-label">M</span><span class="fs-hint">Medium</span>',
  '            </button>',
  '            <button class="sm-fontsize-btn" data-fontsize="large" onclick="SMG.setBarFontSize(\'large\', this)">',
  '              <span class="fs-label">L</span><span class="fs-hint">Large</span>',
  '            </button>',
  '          </div>',
  '        </div>',
  '',
  '        <!-- CARD 4: Colors -->',
  '        <div class="sm-card">',
  '          <div class="sm-card-title"><i class="fas fa-swatchbook"></i> Colors</div>',
  '',
  '          <!-- Quick Theme Presets -->',
  '          <div class="sm-color-sub-label" style="margin-top:0;">Quick Themes</div>',
  '          <div class="sm-preset-row" id="presetRow">',
  '            <button class="sm-preset-btn active" data-preset="classic" onclick="SMG.setPreset(\'classic\', this)">',
  '              <div class="sm-preset-colors"><span style="background:#1E3A5F;"></span><span style="background:#F4A261;"></span><span style="background:rgba(30,58,95,0.95);"></span></div>',
  '              <span class="sm-preset-label">Classic</span>',
  '            </button>',
  '            <button class="sm-preset-btn" data-preset="modern" onclick="SMG.setPreset(\'modern\', this)">',
  '              <div class="sm-preset-colors"><span style="background:#111827;"></span><span style="background:#60A5FA;"></span><span style="background:rgba(31,41,55,0.95);"></span></div>',
  '              <span class="sm-preset-label">Modern</span>',
  '            </button>',
  '            <button class="sm-preset-btn" data-preset="fresh" onclick="SMG.setPreset(\'fresh\', this)">',
  '              <div class="sm-preset-colors"><span style="background:#0D9488;"></span><span style="background:#FCD34D;"></span><span style="background:rgba(0,0,0,0.88);"></span></div>',
  '              <span class="sm-preset-label">Fresh</span>',
  '            </button>',
  '            <button class="sm-preset-btn" data-preset="bold" onclick="SMG.setPreset(\'bold\', this)">',
  '              <div class="sm-preset-colors"><span style="background:#9F1239;"></span><span style="background:#FCD34D;"></span><span style="background:rgba(0,0,0,0.88);"></span></div>',
  '              <span class="sm-preset-label">Bold</span>',
  '            </button>',
  '            <button class="sm-preset-btn" data-preset="elegant" onclick="SMG.setPreset(\'elegant\', this)">',
  '              <div class="sm-preset-colors"><span style="background:#5B21B6;"></span><span style="background:#C084FC;"></span><span style="background:rgba(31,41,55,0.95);"></span></div>',
  '              <span class="sm-preset-label">Elegant</span>',
  '            </button>',
  '            <button class="sm-preset-btn" data-preset="luxe" onclick="SMG.setPreset(\'luxe\', this)">',
  '              <div class="sm-preset-colors"><span style="background:#475569;"></span><span style="background:#F4A261;"></span><span style="background:rgba(0,0,0,0.88);"></span></div>',
  '              <span class="sm-preset-label">Luxe</span>',
  '            </button>',
  '            <button class="sm-preset-btn" data-preset="warm" onclick="SMG.setPreset(\'warm\', this)">',
  '              <div class="sm-preset-colors"><span style="background:#EA580C;"></span><span style="background:#FFFFFF; border:1px solid #D1D5DB;"></span><span style="background:rgba(31,41,55,0.95);"></span></div>',
  '              <span class="sm-preset-label">Warm</span>',
  '            </button>',
  '            <button class="sm-preset-btn" data-preset="coastal" onclick="SMG.setPreset(\'coastal\', this)">',
  '              <div class="sm-preset-colors"><span style="background:#2563EB;"></span><span style="background:#34D399;"></span><span style="background:rgba(255,255,255,0.95); border:1px solid #D1D5DB;"></span></div>',
  '              <span class="sm-preset-label">Coastal</span>',
  '            </button>',
  '            <button class="sm-preset-btn" data-preset="corporate" onclick="SMG.setPreset(\'corporate\', this)">',
  '              <div class="sm-preset-colors"><span style="background:#111827;"></span><span style="background:#FFFFFF; border:1px solid #D1D5DB;"></span><span style="background:rgba(30,58,95,0.95);"></span></div>',
  '              <span class="sm-preset-label">Corporate</span>',
  '            </button>',
  '          </div>',
  '',
  '          <!-- Background Color -->',
  '          <div class="sm-color-sub-label">Background</div>',
  '          <div class="sm-color-row" id="bgColorRow">',
  '            <div class="sm-color-swatch active" style="background: #1E3A5F;" data-color="navy" onclick="SMG.setColor(\'navy\', this)" title="Navy"></div>',
  '            <div class="sm-color-swatch" style="background: #2563EB;" data-color="blue" onclick="SMG.setColor(\'blue\', this)" title="Blue"></div>',
  '            <div class="sm-color-swatch" style="background: #0D9488;" data-color="teal" onclick="SMG.setColor(\'teal\', this)" title="Teal"></div>',
  '            <div class="sm-color-swatch" style="background: #059669;" data-color="green" onclick="SMG.setColor(\'green\', this)" title="Green"></div>',
  '            <div class="sm-color-swatch" style="background: #7C3AED;" data-color="purple" onclick="SMG.setColor(\'purple\', this)" title="Purple"></div>',
  '            <div class="sm-color-swatch" style="background: #DC2626;" data-color="red" onclick="SMG.setColor(\'red\', this)" title="Red"></div>',
  '            <div class="sm-color-swatch" style="background: #9F1239;" data-color="maroon" onclick="SMG.setColor(\'maroon\', this)" title="Maroon"></div>',
  '            <div class="sm-color-swatch" style="background: #EA580C;" data-color="orange" onclick="SMG.setColor(\'orange\', this)" title="Orange"></div>',
  '            <div class="sm-color-swatch" style="background: #475569;" data-color="slate" onclick="SMG.setColor(\'slate\', this)" title="Slate"></div>',
  '            <div class="sm-color-swatch" style="background: #111827;" data-color="dark" onclick="SMG.setColor(\'dark\', this)" title="Dark"></div>',
  '            <div class="sm-color-picker-wrap">',
  '              <div class="sm-color-swatch sm-picker-swatch" id="bgPickerSwatch" style="background: linear-gradient(135deg, #ff0000, #00ff00, #0000ff);" title="Custom Color"></div>',
  '              <input type="color" id="bgColorPicker" class="sm-color-picker-input" value="#1E3A5F" onchange="SMG.setCustomBg(this.value)" oninput="SMG.setCustomBg(this.value)">',
  '            </div>',
  '          </div>',
  '',
  '          <!-- Accent Color -->',
  '          <div class="sm-color-sub-label">Price / Badge Accent</div>',
  '          <div class="sm-color-row" id="accentColorRow">',
  '            <div class="sm-color-swatch active" style="background: #F4A261;" data-accentcolor="gold" onclick="SMG.setAccentColor(\'gold\', this)" title="Gold"></div>',
  '            <div class="sm-color-swatch" style="background: #FCD34D;" data-accentcolor="yellow" onclick="SMG.setAccentColor(\'yellow\', this)" title="Yellow"></div>',
  '            <div class="sm-color-swatch" style="background: #FB923C;" data-accentcolor="orange" onclick="SMG.setAccentColor(\'orange\', this)" title="Orange"></div>',
  '            <div class="sm-color-swatch" style="background: #34D399;" data-accentcolor="mint" onclick="SMG.setAccentColor(\'mint\', this)" title="Mint"></div>',
  '            <div class="sm-color-swatch" style="background: #A3E635;" data-accentcolor="lime" onclick="SMG.setAccentColor(\'lime\', this)" title="Lime"></div>',
  '            <div class="sm-color-swatch" style="background: #60A5FA;" data-accentcolor="sky" onclick="SMG.setAccentColor(\'sky\', this)" title="Sky Blue"></div>',
  '            <div class="sm-color-swatch" style="background: #3B82F6;" data-accentcolor="royal" onclick="SMG.setAccentColor(\'royal\', this)" title="Royal Blue"></div>',
  '            <div class="sm-color-swatch" style="background: #2563EB;" data-accentcolor="blue" onclick="SMG.setAccentColor(\'blue\', this)" title="Blue"></div>',
  '            <div class="sm-color-swatch" style="background: #1E40AF;" data-accentcolor="navy" onclick="SMG.setAccentColor(\'navy\', this)" title="Navy Blue"></div>',
  '            <div class="sm-color-swatch" style="background: #4338CA;" data-accentcolor="indigo" onclick="SMG.setAccentColor(\'indigo\', this)" title="Indigo"></div>',
  '            <div class="sm-color-swatch" style="background: #C084FC;" data-accentcolor="lavender" onclick="SMG.setAccentColor(\'lavender\', this)" title="Lavender"></div>',
  '            <div class="sm-color-swatch" style="background: #F87171;" data-accentcolor="coral" onclick="SMG.setAccentColor(\'coral\', this)" title="Coral"></div>',
  '            <div class="sm-color-swatch" style="background: #FFFFFF; border: 2px solid #D1D5DB;" data-accentcolor="white" onclick="SMG.setAccentColor(\'white\', this)" title="White"></div>',
  '            <div class="sm-color-picker-wrap">',
  '              <div class="sm-color-swatch sm-picker-swatch" id="accentPickerSwatch" style="background: linear-gradient(135deg, #ff0000, #00ff00, #0000ff);" title="Custom Color"></div>',
  '              <input type="color" id="accentColorPicker" class="sm-color-picker-input" value="#F4A261" onchange="SMG.setCustomAccent(this.value)" oninput="SMG.setCustomAccent(this.value)">',
  '            </div>',
  '          </div>',
  '',
  '          <!-- Bottom Bar Color -->',
  '          <div class="sm-color-sub-label">Bottom Bar</div>',
  '          <div class="sm-color-row" id="barColorRow">',
  '            <div class="sm-color-swatch active" style="background: #000000;" data-barcolor="black" onclick="SMG.setBarColor(\'black\', this)" title="Black"></div>',
  '            <div class="sm-color-swatch" style="background: #1E3A5F;" data-barcolor="navy" onclick="SMG.setBarColor(\'navy\', this)" title="Navy"></div>',
  '            <div class="sm-color-swatch" style="background: #2563EB;" data-barcolor="blue" onclick="SMG.setBarColor(\'blue\', this)" title="Blue"></div>',
  '            <div class="sm-color-swatch" style="background: #059669;" data-barcolor="green" onclick="SMG.setBarColor(\'green\', this)" title="Green"></div>',
  '            <div class="sm-color-swatch" style="background: #0D9488;" data-barcolor="teal" onclick="SMG.setBarColor(\'teal\', this)" title="Teal"></div>',
  '            <div class="sm-color-swatch" style="background: #7C3AED;" data-barcolor="purple" onclick="SMG.setBarColor(\'purple\', this)" title="Purple"></div>',
  '            <div class="sm-color-swatch" style="background: #991B1B;" data-barcolor="red" onclick="SMG.setBarColor(\'red\', this)" title="Red"></div>',
  '            <div class="sm-color-swatch" style="background: #1F2937;" data-barcolor="dark" onclick="SMG.setBarColor(\'dark\', this)" title="Charcoal"></div>',
  '            <div class="sm-color-swatch" style="background: #FFFFFF; border: 2px solid #D1D5DB;" data-barcolor="white" onclick="SMG.setBarColor(\'white\', this)" title="White"></div>',
  '            <div class="sm-color-picker-wrap">',
  '              <div class="sm-color-swatch sm-picker-swatch" id="barPickerSwatch" style="background: linear-gradient(135deg, #ff0000, #00ff00, #0000ff);" title="Custom Color"></div>',
  '              <input type="color" id="barColorPicker" class="sm-color-picker-input" value="#000000" onchange="SMG.setCustomBar(this.value)" oninput="SMG.setCustomBar(this.value)">',
  '            </div>',
  '          </div>',
  '        </div>',
  '',
  '        <!-- CARD 5: Branding -->',
  '        <div class="sm-card">',
  '          <div class="sm-card-title"><i class="fas fa-id-badge"></i> Your Branding</div>',
  '          <div class="sm-upload-row">',
  '            <div class="sm-upload-box">',
  '              <div class="sm-upload-preview" id="headshotPreview" onclick="document.getElementById(\'headshotInput\').click()">',
  '                <i class="fas fa-user upload-icon" id="headshotIcon"></i>',
  '                <img id="headshotImg" src="" alt="Headshot" style="display:none;" />',
  '              </div>',
  '              <span class="sm-upload-label">Headshot</span>',
  '              <div class="sm-upload-actions">',
  '                <button class="sm-upload-btn" onclick="document.getElementById(\'headshotInput\').click()"><i class="fas fa-upload"></i> Upload</button>',
  '                <button class="sm-upload-btn remove" id="headshotRemoveBtn" onclick="SMG.removeImage(\'headshot\')" style="display:none;"><i class="fas fa-times"></i></button>',
  '              </div>',
  '              <input type="file" id="headshotInput" accept="image/*" onchange="SMG.handleUpload(event, \'headshot\')" style="display:none;" />',
  '            </div>',
  '            <div class="sm-upload-box">',
  '              <div class="sm-upload-preview logo-preview" id="logoPreview" onclick="document.getElementById(\'logoInput\').click()">',
  '                <i class="fas fa-building upload-icon" id="logoIcon"></i>',
  '                <img id="logoImg" src="" alt="Logo" style="display:none;" />',
  '              </div>',
  '              <span class="sm-upload-label">Company Logo</span>',
  '              <div class="sm-upload-actions">',
  '                <button class="sm-upload-btn" onclick="document.getElementById(\'logoInput\').click()"><i class="fas fa-upload"></i> Upload</button>',
  '                <button class="sm-upload-btn remove" id="logoRemoveBtn" onclick="SMG.removeImage(\'logo\')" style="display:none;"><i class="fas fa-times"></i></button>',
  '              </div>',
  '              <input type="file" id="logoInput" accept="image/*" onchange="SMG.handleUpload(event, \'logo\')" style="display:none;" />',
  '            </div>',
  '          </div>',
  '          <div class="field-hint" style="text-align:center; margin-top:8px; font-size:11px; color:#9CA3AF;">Auto-loaded from Settings if available</div>',
  '',
  '          <!-- Home Photo and Realtor Photo are now in the dynamic fields area, not here -->',
  '',
  '',
  '        </div>',
  '',
  '      </div>',
  '',
  '      <!-- COLUMN 2 — Data Entry -->',
  '      <div class="sm-col">',
  '',
  '        <!-- Dynamic content cards (generated by engine) -->',
  '        <div id="dynamicFieldsContainer"></div>',
  '',
  '        <!-- CARD 7: Agent Info -->',
  '        <div class="sm-card">',
  '          <div class="sm-card-title"><i class="fas fa-user-tie"></i> Your Info</div>',
  '          <div class="sm-field">',
  '            <label>Your Name</label>',
  '            <input type="text" id="agentName" placeholder="Jane Smith" oninput="SMG.onInput()">',
  '          </div>',
  '          <div class="sm-field">',
  '            <label>Title / Company</label>',
  '            <input type="text" id="agentTitle" placeholder="Loan Officer | ABC Mortgage" oninput="SMG.onInput()">',
  '          </div>',
  '          <div class="sm-field-row">',
  '            <div class="sm-field">',
  '              <label>NMLS #</label>',
  '              <input type="text" id="agentNmls" placeholder="123456" oninput="SMG.onInput()">',
  '            </div>',
  '            <div class="sm-field">',
  '              <label>Phone</label>',
  '              <input type="tel" id="agentPhone" placeholder="(555) 123-4567" oninput="SMG.onInput()">',
  '            </div>',
  '          </div>',
  '          <div class="sm-field">',
  '            <label>Email</label>',
  '            <input type="email" id="agentEmail" placeholder="jane@abcmortgage.com" oninput="SMG.onInput()">',
  '          </div>',
  '          <div class="sm-field">',
  '            <label>Website</label>',
  '            <input type="text" id="agentWebsite" placeholder="www.abcmortgage.com" oninput="SMG.onInput()">',
  '            <div class="field-hint">Displayed under your logo in the bottom bar</div>',
  '          </div>',
  '',
  '          <div class="sm-card-divider"></div>',
  '',
  '          <div class="sm-color-sub-label" style="margin-top:0;">Disclaimer Bar (below agent bar)</div>',
  '          <div class="sm-field">',
  '            <label>Disclaimer Left</label>',
  '            <textarea id="disclaimerLeft" placeholder="Company Name NMLS# 123456&#10;Licensed Mortgage Broker" rows="2" oninput="SMG.onInput()"></textarea>',
  '          </div>',
  '          <div class="sm-field">',
  '            <label>Disclaimer Right</label>',
  '            <textarea id="disclaimerRight" placeholder="Corporate Address Line 1&#10;City, State ZIP" rows="2" oninput="SMG.onInput()"></textarea>',
  '          </div>',
  '',
  '          <div class="sm-ehl-upload-area">',
  '            <div class="sm-ehl-upload-preview" id="ehlPreview" onclick="document.getElementById(\'ehlInput\').click()">',
  '              <i class="fas fa-home upload-icon" id="ehlIcon"></i>',
  '              <img id="ehlImg" src="" alt="EHL Logo" style="display:none; width:100%; height:100%; object-fit:contain;" />',
  '            </div>',
  '            <div class="sm-ehl-upload-info">',
  '              <span class="sm-upload-label">Equal Housing Lender Logo</span>',
  '              <div class="sm-upload-actions">',
  '                <button class="sm-upload-btn" onclick="document.getElementById(\'ehlInput\').click()"><i class="fas fa-upload"></i> Upload</button>',
  '                <button class="sm-upload-btn remove" id="ehlRemoveBtn" onclick="SMG.removeImage(\'ehlLogo\')" style="display:none;"><i class="fas fa-times"></i></button>',
  '              </div>',
  '            </div>',
  '            <input type="file" id="ehlInput" accept="image/*" onchange="SMG.handleUpload(event, \'ehlLogo\')" style="display:none;" />',
  '          </div>',
  '          <div class="field-hint" style="font-size:11px; color:#9CA3AF; margin-top:6px;">Upload your EHL logo. It appears on the far right of the disclaimer bar.</div>',
  '        </div>',
  '',
  '      </div>',
  '',
  '      <!-- COLUMN 3 — Live Preview -->',
  '      <div class="sm-preview-panel">',
  '        <div class="sm-preview-card">',
  '          <div class="sm-preview-header">',
  '            <span class="sm-preview-title"><i class="fas fa-eye" style="margin-right:6px;"></i> Live Preview</span>',
  '            <span class="sm-preview-size-label" id="previewSizeLabel">1080 &times; 1080</span>',
  '          </div>',
  '          <div class="sm-canvas-wrapper">',
  '            <canvas id="smCanvas" width="1080" height="1080"></canvas>',
  '          </div>',
  '          <div class="sm-download-row">',
  '            <button class="sm-download-btn primary" onclick="SMG.download()"><i class="fas fa-download"></i> Download PNG</button>',
  '            <button class="sm-download-btn secondary" onclick="SMG.downloadAll()"><i class="fas fa-layer-group"></i> All 3 Sizes</button>',
  '          </div>',
  '        </div>',
  '',
  '        <!-- POST CAPTION GENERATOR -->',
  '        <div class="sm-caption-card">',
  '          <div class="sm-caption-header">',
  '            <span class="sm-caption-title"><i class="fas fa-comment-alt" style="margin-right:6px;"></i> Post Caption</span>',
  '            <button class="sm-caption-copy-btn" id="captionCopyBtn" onclick="SMG.copyCaption()">',
  '              <i class="fas fa-copy"></i> <span id="captionCopyLabel">Copy</span>',
  '            </button>',
  '          </div>',
  '          <textarea class="sm-caption-text" id="captionText" readonly placeholder="Fill in your content fields to generate a post caption..."></textarea>',
  '          <div class="sm-caption-hint">Auto-generated from your inputs. Edit after copying if needed.</div>',
  '        </div>',
  '      </div>',
  '',
  '    </div>',
  '  </div>',
  '</div>'
].join('\n');

// --- Mount Logic ---
// Finds or waits for the #social-media-app mount point, injects HTML, then loads the engine
function mount() {
  var container = document.getElementById('social-media-app');
  if (container) {
    container.innerHTML = PAGE_HTML;
    loadEngine();
  } else {
    // Poll for mount point (Webflow may render it asynchronously)
    var attempts = 0;
    var interval = setInterval(function() {
      attempts++;
      var el = document.getElementById('social-media-app');
      if (el) {
        clearInterval(interval);
        el.innerHTML = PAGE_HTML;
        loadEngine();
      } else if (attempts > 100) {
        clearInterval(interval);
        console.error('Social Media Graphics: #social-media-app element not found on page.');
      }
    }, 50);
  }
}

// Load the SMG canvas engine script from the Cloudflare Worker
function loadEngine() {
  var s = document.createElement('script');
  s.src = ENGINE_URL;
  s.onload = function() {
    // In SPA navigation (React Router), DOMContentLoaded already fired before
    // the engine loaded, so the engine's DOMContentLoaded listener won't fire.
    // We call init() directly to ensure fields are built and data is restored.
    if (document.readyState !== 'loading' && typeof SMG !== 'undefined' && SMG.init) {
      SMG.init();
    }
  };
  document.head.appendChild(s);
}

// Run immediately if DOM is ready, otherwise wait
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', mount);
} else {
  mount();
}
